/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module incomp_if2(i0, i1, i2, i3, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input i0;
  input i1;
  input i2;
  input i3;
  output y;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(_03_),
    .B(_04_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _12_ (
    .A1(_04_),
    .A2(_08_),
    .B1(_09_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__or2_2 _13_ (
    .A(_04_),
    .B(_06_),
    .X(_07_)
  );
  \$_DLATCH_P_  _14_ (
    .D(_00_),
    .E(_01_),
    .Q(y)
  );
  assign _02_ = i3;
  assign _03_ = i1;
  assign _04_ = i0;
  assign _00_ = _05_;
  assign _06_ = i2;
  assign _01_ = _07_;
endmodule
