/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module opt_check3(a, b, c, y);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input a;
  input b;
  input c;
  output y;
  sky130_fd_sc_hd__and3_2 _5_ (
    .A(_1_),
    .B(_2_),
    .C(_3_),
    .X(_4_)
  );
  assign _1_ = b;
  assign _2_ = c;
  assign _3_ = a;
  assign y = _4_;
endmodule
