/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module opt_check4(a, b, c, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input a;
  input b;
  input c;
  output y;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(_03_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(_04_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _13_ (
    .A(_06_),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _14_ (
    .A(_03_),
    .B(_04_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _15_ (
    .A(_09_),
    .B(_10_),
    .Y(_07_)
  );
  assign _03_ = c;
  assign _04_ = a;
  assign _05_ = b;
  assign y = _07_;
endmodule
