/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module dff_const4(clk, set, q);
  input clk;
  output q;
  input set;
  assign q = 1'b1;
endmodule
