/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module dff_syncasync_reset(clk, async_reset, sync_reset, d, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input async_reset;
  input clk;
  input d;
  output q;
  input sync_reset;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and2b_2 _09_ (
    .A_N(_06_),
    .B(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(clk),
    .D(_00_),
    .Q(q),
    .RESET_B(_07_)
  );
  assign _02_ = async_reset;
  assign _07_ = _03_;
  assign _04_ = d;
  assign _00_ = _05_;
  assign _06_ = sync_reset;
endmodule
