/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module counter_opt1(clk, reset, q);
  wire [2:0] _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire [2:0] count;
  output q;
  input reset;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_1_),
    .Y(_2_)
  );
  reg \count_reg[0] ;
  always @(posedge clk or posedge reset)
    if (reset)
      \count_reg[0]  <= 0;
    else
      \count_reg[0]  <= _0_[0];
  assign count[0] = \count_reg[0] ;
  assign q = count[0];
  assign _1_ = count[0];
  assign _0_[0] = _2_;
endmodule
