/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module counter_opt2(clk, reset, q);
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  input clk;
  reg [2:0] count;
  output q;
  input reset;
  assign _02_ = ~(count[1] | count[0]);
  assign q = _02_ & count[2];
  assign _00_[0] = ~count[0];
  assign _00_[1] = count[1] ^ count[0];
  assign _01_ = count[1] & count[0];
  assign _00_[2] = _01_ ^ count[2];
  always @(posedge clk or posedge reset)
    if (reset)
      count[0] <= 0;
    else
      count[0] <= _00_[0];
  always @(posedge clk or posedge reset)
    if (reset)
      count[1] <= 0;
    else
      count[1] <= _00_[1];
  always @(posedge clk or posedge reset)
    if (reset)
      count[2] <= 0;
    else
      count[2] <= _00_[2];
endmodule
