/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "mux_for.v:1" *)
module mux_for(i0, i1, i2, i3, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "mux_for.v:2" *)
  input i0;
  (* src = "mux_for.v:3" *)
  input i1;
  (* src = "mux_for.v:4" *)
  input i2;
  (* src = "mux_for.v:5" *)
  input i3;
  (* src = "mux_for.v:11" *)
  wire [3:0] i_int;
  (* src = "mux_for.v:6" *)
  input [1:0] sel;
  (* src = "mux_for.v:7" *)
  output y;
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(_08_),
    .B(_11_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(_08_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _23_ (
    .A1(_14_),
    .A2(_20_),
    .B1(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(_09_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__or2b_2 _25_ (
    .A(_19_),
    .B_N(_08_),
    .X(_13_)
  );
  sky130_fd_sc_hd__o211ai_1 _26_ (
    .A1(_08_),
    .A2(_17_),
    .B1(_12_),
    .C1(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21ai_0 _27_ (
    .A1(_18_),
    .A2(_10_),
    .B1(_15_),
    .Y(_16_)
  );
  assign i_int = { i3, i2, i1, i0 };
  assign _08_ = sel[0];
  assign _09_ = sel[1];
  assign _17_ = i0;
  assign _19_ = i1;
  assign _11_ = i2;
  assign _14_ = i3;
  assign y = _16_;
endmodule
