/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module incomp_case(i0, i1, i2, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input i0;
  input i1;
  input i2;
  input [1:0] sel;
  output y;
  sky130_fd_sc_hd__clkinv_1 _14_ (
    .A(_08_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__and2b_2 _15_ (
    .A_N(_05_),
    .B(_07_),
    .X(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(_05_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand3_1 _17_ (
    .A(_12_),
    .B(_07_),
    .C(_09_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _18_ (
    .A1(_11_),
    .A2(_13_),
    .B1(_06_),
    .Y(_10_)
  );
  \$_DLATCH_P_  _19_ (
    .D(_00_),
    .E(_04_),
    .Q(y)
  );
  assign _05_ = sel[1];
  assign _07_ = sel[0];
  assign _08_ = i0;
  assign _09_ = i1;
  assign _00_ = _10_;
  assign _04_ = _12_;
endmodule
