/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module partial_case_assign(i0, i1, i2, sel, y, x);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input i0;
  input i1;
  input i2;
  input [1:0] sel;
  output x;
  output y;
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(_01_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(_15_),
    .B(_14_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(_14_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand3_1 _26_ (
    .A(_03_),
    .B(_15_),
    .C(_06_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(_12_),
    .B(_01_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand3b_1 _28_ (
    .A_N(_01_),
    .B(_14_),
    .C(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand3_1 _29_ (
    .A(_05_),
    .B(_07_),
    .C(_08_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _30_ (
    .A(_03_),
    .B(_15_),
    .C(_12_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _31_ (
    .A1(_14_),
    .A2(_01_),
    .B1(_02_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _32_ (
    .A(_09_),
    .B(_10_),
    .Y(_04_)
  );
  \$_DLATCH_P_  _33_ (
    .D(_00_),
    .E(_21_),
    .Q(x)
  );
  assign _21_ = _11_;
  assign _12_ = i2;
  assign y = _13_;
  assign _14_ = sel[0];
  assign _01_ = sel[1];
  assign _02_ = i1;
  assign _00_ = _04_;
  assign _06_ = i0;
endmodule
